import type { Property, BlogPost, Lead } from "./types";

/**
 * Rich demo dataset used when Supabase is not configured.
 * Images reference real photos copied into /public/properties.
 * This keeps the site fully functional and presentable in DEMO mode.
 */

const now = "2026-06-01T09:00:00.000Z";

function imgs(propertyId: string, files: string[]): Property["images"] {
  return files.map((f, i) => ({
    id: `${propertyId}-img-${i}`,
    property_id: propertyId,
    url: `/properties/${f}`,
    alt: null,
    sort_order: i,
    is_cover: i === 0,
  }));
}

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "p-001",
    slug: "sunset-ridge-pool-villa-bang-tao",
    title: "Sunset Ridge — Sea-View Pool Villa",
    description:
      "Perched on an elevated plot above Bang Tao, Sunset Ridge is a contemporary four-bedroom villa where floor-to-ceiling glass dissolves the line between living space and infinity pool. West-facing terraces frame uninterrupted sunsets over the Andaman Sea, while the open-plan living pavilion flows to a fully fitted European kitchen. A signature Islander Home residence for the discerning buyer.",
    listing_type: "sale",
    status: "available",
    property_type: "Villa",
    area_slug: "bang-tao",
    price: 38500000,
    rent_period: null,
    bedrooms: 4,
    bathrooms: 5,
    living_area: 420,
    land_area: 800,
    address: "Cherng Talay, Bang Tao, Phuket",
    latitude: 7.9989,
    longitude: 98.2945,
    features: [
      "Infinity pool",
      "Panoramic sea view",
      "Smart-home automation",
      "Private gym",
      "Covered parking for 3",
      "24/7 estate security",
      "European kitchen",
      "Maid's quarters",
    ],
    is_featured: true,
    reference: "IHP-V001",
    created_at: now,
    updated_at: now,
    images: imgs("p-001", ["villa-1.png", "villa-3.png", "interior-1.jpg", "interior-2.jpg", "interior-5.jpg"]),
  },
  {
    id: "p-002",
    slug: "the-andaman-infinity-villa-rawai",
    title: "The Andaman — Infinity Villa",
    description:
      "A serene three-bedroom retreat above Rawai with a horizon-edge pool that appears to spill into the sea. Designed around indoor-outdoor living, with a sunken lounge, tropical garden and a master suite opening to a private sun deck. Minutes from Nai Harn beach and Rawai's seafront dining.",
    listing_type: "sale",
    status: "available",
    property_type: "Villa",
    area_slug: "rawai",
    price: 24900000,
    rent_period: null,
    bedrooms: 3,
    bathrooms: 4,
    living_area: 310,
    land_area: 560,
    address: "Rawai, Mueang Phuket",
    latitude: 7.7741,
    longitude: 98.3245,
    features: [
      "Infinity-edge pool",
      "Sea view",
      "Tropical garden",
      "Open-plan living",
      "Solar hot water",
      "Carport",
    ],
    is_featured: true,
    reference: "IHP-V002",
    created_at: now,
    updated_at: now,
    images: imgs("p-002", ["villa-6.png", "villa-7.png", "interior-6.jpg", "interior-8.jpg"]),
  },
  {
    id: "p-003",
    slug: "laguna-grande-residence-bang-tao",
    title: "Laguna Grande — Branded Residence",
    description:
      "An elegant five-bedroom estate within a gated Laguna enclave. Double-height ceilings, a private spa pavilion and a 15-metre lap pool set the tone for resort-grade living, with full access to Laguna's golf course, beach clubs and five-star amenities.",
    listing_type: "sale",
    status: "available",
    property_type: "Villa",
    area_slug: "bang-tao",
    price: 62000000,
    rent_period: null,
    bedrooms: 5,
    bathrooms: 6,
    living_area: 560,
    land_area: 1100,
    address: "Laguna, Bang Tao, Phuket",
    latitude: 8.0009,
    longitude: 98.2987,
    features: [
      "15m lap pool",
      "Private spa pavilion",
      "Golf course access",
      "Beach club membership",
      "Home cinema",
      "Double garage",
      "Backup generator",
    ],
    is_featured: true,
    reference: "IHP-V003",
    created_at: now,
    updated_at: now,
    images: imgs("p-003", ["villa-2.png", "villa-5.png", "interior-9.jpg", "interior-10.jpg", "interior-12.jpg"]),
  },
  {
    id: "p-004",
    slug: "hillcrest-villa-chalong",
    title: "Hillcrest — Mountain & Sea View Villa",
    description:
      "Tucked into the Chalong hillside, this four-bedroom family villa balances privacy with sweeping views toward Big Buddha and Chalong Bay. A generous open kitchen, covered terrace and saltwater pool make it ideal for year-round island living.",
    listing_type: "sale",
    status: "available",
    property_type: "Villa",
    area_slug: "chalong",
    price: 18900000,
    rent_period: null,
    bedrooms: 4,
    bathrooms: 4,
    living_area: 280,
    land_area: 600,
    address: "Chalong, Mueang Phuket",
    latitude: 7.8462,
    longitude: 98.3381,
    features: [
      "Saltwater pool",
      "Mountain & sea view",
      "Covered terrace",
      "Open kitchen",
      "Fruit garden",
      "Parking for 2",
    ],
    is_featured: false,
    reference: "IHP-V004",
    created_at: now,
    updated_at: now,
    images: imgs("p-004", ["villa-4.png", "villa-8.png", "interior-14.jpg", "interior-16.jpg"]),
  },
  {
    id: "p-005",
    slug: "the-quarter-condo-koh-kaew",
    title: "The Quarter — Modern 2-Bed Condo",
    description:
      "A bright, fully-furnished two-bedroom condominium in a low-rise resort community at Koh Kaew. Walk to Central Floresta and international schools, with a communal pool, gym and co-working lounge on site. Turn-key and tenant-ready.",
    listing_type: "sale",
    status: "available",
    property_type: "Condominium",
    area_slug: "koh-kaew",
    price: 6900000,
    rent_period: null,
    bedrooms: 2,
    bathrooms: 2,
    living_area: 72,
    land_area: null,
    address: "Koh Kaew, Mueang Phuket",
    latitude: 7.9335,
    longitude: 98.3786,
    features: [
      "Fully furnished",
      "Communal pool & gym",
      "Co-working lounge",
      "Walk to Central Floresta",
      "Covered parking",
      "Foreign freehold quota",
    ],
    is_featured: true,
    reference: "IHP-C005",
    created_at: now,
    updated_at: now,
    images: imgs("p-005", ["interior-1.jpg", "interior-3.jpg", "interior-4.jpg", "interior-7.jpg"]),
  },
  {
    id: "p-006",
    slug: "old-town-shophouse-phuket-town",
    title: "Heritage Shophouse — Old Phuket Town",
    description:
      "A beautifully restored Sino-Portuguese shophouse on a characterful Old Town lane. Three storeys of flexible space — perfect as a boutique residence, café or creative studio — with original detailing and a sunlit rear courtyard.",
    listing_type: "sale",
    status: "available",
    property_type: "Townhouse",
    area_slug: "phuket-town",
    price: 12500000,
    rent_period: null,
    bedrooms: 3,
    bathrooms: 3,
    living_area: 210,
    land_area: 120,
    address: "Old Town, Phuket City",
    latitude: 7.8804,
    longitude: 98.3923,
    features: [
      "Restored heritage façade",
      "Three storeys",
      "Rear courtyard",
      "Commercial-residential use",
      "Walk to Walking Street",
    ],
    is_featured: false,
    reference: "IHP-T006",
    created_at: now,
    updated_at: now,
    images: imgs("p-006", ["interior-11.jpg", "interior-13.jpg", "interior-15.jpg"]),
  },
  {
    id: "p-007",
    slug: "palm-grove-rental-villa-bang-tao",
    title: "Palm Grove — Private Pool Villa (Rental)",
    description:
      "A turn-key three-bedroom pool villa available for long-term rental in a quiet Bang Tao residence. Fully furnished with a tropical garden, private pool and a short drive to Bang Tao beach and Boat Avenue.",
    listing_type: "rent",
    status: "available",
    property_type: "Villa",
    area_slug: "bang-tao",
    price: 120000,
    rent_period: "month",
    bedrooms: 3,
    bathrooms: 3,
    living_area: 240,
    land_area: 480,
    address: "Cherng Talay, Bang Tao",
    latitude: 7.9959,
    longitude: 98.2967,
    features: [
      "Private pool",
      "Fully furnished",
      "Tropical garden",
      "Pet friendly",
      "Weekly pool & garden care",
      "High-speed fibre internet",
    ],
    is_featured: true,
    reference: "IHP-R007",
    created_at: now,
    updated_at: now,
    images: imgs("p-007", ["villa-3.png", "interior-2.jpg", "interior-5.jpg", "interior-8.jpg"]),
  },
  {
    id: "p-008",
    slug: "seabreeze-apartment-rawai",
    title: "Seabreeze — 1-Bed Apartment (Rental)",
    description:
      "A stylish one-bedroom apartment a few minutes from Rawai beach, ideal for long-stay residents and remote workers. Includes a communal pool, gym and a dedicated workspace nook.",
    listing_type: "rent",
    status: "available",
    property_type: "Apartment",
    area_slug: "rawai",
    price: 35000,
    rent_period: "month",
    bedrooms: 1,
    bathrooms: 1,
    living_area: 48,
    land_area: null,
    address: "Rawai, Mueang Phuket",
    latitude: 7.7755,
    longitude: 98.326,
    features: [
      "Communal pool & gym",
      "Furnished",
      "Workspace nook",
      "Near Rawai beach",
      "Covered parking",
    ],
    is_featured: false,
    reference: "IHP-R008",
    created_at: now,
    updated_at: now,
    images: imgs("p-008", ["interior-6.jpg", "interior-7.jpg", "interior-9.jpg"]),
  },
  {
    id: "p-009",
    slug: "garden-house-koh-kaew-rental",
    title: "Garden House — 3-Bed Family Home (Rental)",
    description:
      "A comfortable three-bedroom family house in a friendly Koh Kaew village, close to international schools. Bright open living areas, a fitted kitchen and a private garden — ready for long-term family living.",
    listing_type: "rent",
    status: "available",
    property_type: "House",
    area_slug: "koh-kaew",
    price: 55000,
    rent_period: "month",
    bedrooms: 3,
    bathrooms: 3,
    living_area: 180,
    land_area: 320,
    address: "Koh Kaew, Mueang Phuket",
    latitude: 7.9341,
    longitude: 98.3799,
    features: [
      "Private garden",
      "Fitted kitchen",
      "Near international schools",
      "Furnished",
      "Parking for 2",
      "Pet friendly",
    ],
    is_featured: true,
    reference: "IHP-R009",
    created_at: now,
    updated_at: now,
    images: imgs("p-009", ["interior-10.jpg", "interior-12.jpg", "interior-14.jpg", "interior-16.jpg"]),
  },
  {
    id: "p-013",
    slug: "azure-cove-beachfront-condo-bang-tao",
    title: "Azure Cove — Beachfront Condominium",
    description:
      "A stunning one-bedroom beachfront unit in a boutique low-rise complex on Bang Tao's quieter northern stretch. Wake up to the Andaman Sea from your private balcony, with a shared infinity pool and direct beach access below.",
    listing_type: "sale",
    status: "available",
    property_type: "Condominium",
    area_slug: "bang-tao",
    price: 8900000,
    rent_period: null,
    bedrooms: 1,
    bathrooms: 1,
    living_area: 58,
    land_area: null,
    address: "Bang Tao Beach, Cherng Talay, Phuket",
    latitude: 7.9975,
    longitude: 98.2899,
    features: [
      "Beachfront location",
      "Private balcony with sea view",
      "Shared infinity pool",
      "Direct beach access",
      "Fully furnished",
      "Foreign freehold quota",
    ],
    is_featured: true,
    reference: "IHP-C013",
    created_at: now,
    updated_at: now,
    images: imgs("p-013", ["interior-3.jpg", "interior-5.jpg", "villa-6.png"]),
  },
  {
    id: "p-014",
    slug: "silver-palm-townhouse-thalang",
    title: "Silver Palm — 3-Bed Townhouse",
    description:
      "A contemporary three-bedroom townhouse in a well-managed gated estate near the Thalang intersection. Ideal for families or investors, with a shared clubhouse pool, playground and easy access to international schools and the airport.",
    listing_type: "sale",
    status: "available",
    property_type: "Townhouse",
    area_slug: "thalang",
    price: 7200000,
    rent_period: null,
    bedrooms: 3,
    bathrooms: 3,
    living_area: 160,
    land_area: 220,
    address: "Thalang District, Phuket",
    latitude: 8.0211,
    longitude: 98.3295,
    features: [
      "Gated estate",
      "Shared clubhouse pool",
      "Children's playground",
      "Near international schools",
      "2 covered parking spaces",
      "Low maintenance fees",
    ],
    is_featured: false,
    reference: "IHP-T014",
    created_at: now,
    updated_at: now,
    images: imgs("p-014", ["interior-11.jpg", "interior-13.jpg", "villa-4.png"]),
  },
  {
    id: "p-015",
    slug: "panorama-pool-villa-rawai",
    title: "Panorama — 5-Bed Sea-View Villa",
    description:
      "A grand five-bedroom villa commanding panoramic views from the Rawai hillside south toward Promthep Cape. Designed for entertaining with a 20-metre pool, an outdoor sala, a professional kitchen and a home cinema room.",
    listing_type: "sale",
    status: "available",
    property_type: "Villa",
    area_slug: "rawai",
    price: 49500000,
    rent_period: null,
    bedrooms: 5,
    bathrooms: 6,
    living_area: 580,
    land_area: 1050,
    address: "Rawai Hillside, Mueang Phuket",
    latitude: 7.7699,
    longitude: 98.3307,
    features: [
      "20m infinity pool",
      "Panoramic sea & cape view",
      "Home cinema",
      "Outdoor sala & BBQ",
      "Professional kitchen",
      "Staff quarters",
      "Double garage",
      "Smart-home system",
    ],
    is_featured: true,
    reference: "IHP-V015",
    created_at: now,
    updated_at: now,
    images: imgs("p-015", ["villa-2.png", "villa-5.png", "interior-9.jpg", "interior-10.jpg"]),
  },
  {
    id: "p-016",
    slug: "city-loft-studio-phuket-town",
    title: "City Loft — Designer Studio",
    description:
      "A chic, fully-fitted studio apartment in the heart of Phuket Town, steps from galleries, coffee shops and the weekend market. An ideal pied-à-terre or yield-generating rental unit with strong short-stay demand.",
    listing_type: "sale",
    status: "available",
    property_type: "Condominium",
    area_slug: "phuket-town",
    price: 2800000,
    rent_period: null,
    bedrooms: 1,
    bathrooms: 1,
    living_area: 36,
    land_area: null,
    address: "Phuket City Centre",
    latitude: 7.8843,
    longitude: 98.3867,
    features: [
      "Fully furnished",
      "City-centre location",
      "Communal rooftop terrace",
      "High-speed internet",
      "Foreign freehold quota",
      "Short-stay rental allowed",
    ],
    is_featured: false,
    reference: "IHP-C016",
    created_at: now,
    updated_at: now,
    images: imgs("p-016", ["interior-7.jpg", "interior-8.jpg", "interior-17.jpg"]),
  },
  {
    id: "p-017",
    slug: "mangrove-estate-land-koh-kaew",
    title: "Mangrove Estate — Chanote Land 2 Rai",
    description:
      "A generous 3,200 m² (2 rai) fully-titled Chanote plot in a quiet Koh Kaew pocket, surrounded by mature trees with road access on two sides. Utilities connected to the boundary — ready for a bespoke villa compound or boutique development.",
    listing_type: "sale",
    status: "available",
    property_type: "Land",
    area_slug: "koh-kaew",
    price: 16000000,
    rent_period: null,
    bedrooms: 0,
    bathrooms: 0,
    living_area: null,
    land_area: 3200,
    address: "Koh Kaew, Mueang Phuket",
    latitude: 7.9302,
    longitude: 98.374,
    features: [
      "Chanote title",
      "Dual road access",
      "Utilities at boundary",
      "Mature tree coverage",
      "Flat to gentle gradient",
      "Near international schools",
    ],
    is_featured: false,
    reference: "IHP-L017",
    created_at: now,
    updated_at: now,
    images: imgs("p-017", ["villa-7.png", "villa-8.png"]),
  },
  {
    id: "p-018",
    slug: "seaview-duplex-chalong",
    title: "Seaview Duplex — 2-Bed with Rooftop",
    description:
      "An architecturally distinctive two-bedroom duplex in the Chalong hills, featuring a private rooftop terrace with views to Big Buddha and Chalong Bay. Open-plan living on the main floor flows to a plunge pool terrace — understated luxury at an accessible entry point.",
    listing_type: "sale",
    status: "available",
    property_type: "Townhouse",
    area_slug: "chalong",
    price: 9500000,
    rent_period: null,
    bedrooms: 2,
    bathrooms: 2,
    living_area: 135,
    land_area: 180,
    address: "Chalong Hills, Mueang Phuket",
    latitude: 7.8489,
    longitude: 98.3405,
    features: [
      "Private rooftop terrace",
      "Plunge pool",
      "Big Buddha & bay views",
      "Open-plan living",
      "Covered parking",
      "Low monthly fees",
    ],
    is_featured: false,
    reference: "IHP-T018",
    created_at: now,
    updated_at: now,
    images: imgs("p-018", ["interior-15.jpg", "interior-16.jpg", "villa-4.png"]),
  },
  {
    id: "p-010",
    slug: "northshore-land-plot-thalang",
    title: "Northshore — Premium Land Plot",
    description:
      "A rare 1,600 m² Chanote land plot in Thalang's emerging north, with road access, electricity at the boundary and gentle elevation suited to a sea-glimpse villa development. A strategic long-term hold close to the airport and Laguna.",
    listing_type: "sale",
    status: "available",
    property_type: "Land",
    area_slug: "thalang",
    price: 9800000,
    rent_period: null,
    bedrooms: 0,
    bathrooms: 0,
    living_area: null,
    land_area: 1600,
    address: "Thalang District, Phuket",
    latitude: 8.0353,
    longitude: 98.339,
    features: [
      "Chanote title",
      "Road access",
      "Utilities at boundary",
      "Gentle elevation",
      "Near airport & Laguna",
    ],
    is_featured: false,
    reference: "IHP-L010",
    created_at: now,
    updated_at: now,
    images: imgs("p-010", ["villa-7.png", "villa-8.png"]),
  },
  {
    id: "p-011",
    slug: "the-residence-penthouse-phuket-town",
    title: "The Residence — Town Penthouse",
    description:
      "A sophisticated two-bedroom penthouse in central Phuket Town with skyline views, a private rooftop terrace and premium fittings throughout. Walkable to the best of Old Town's cafés and culture.",
    listing_type: "sale",
    status: "reserved",
    property_type: "Condominium",
    area_slug: "phuket-town",
    price: 8400000,
    rent_period: null,
    bedrooms: 2,
    bathrooms: 2,
    living_area: 96,
    land_area: null,
    address: "Phuket City",
    latitude: 7.8829,
    longitude: 98.39,
    features: [
      "Private rooftop terrace",
      "Skyline views",
      "Premium fittings",
      "Communal pool",
      "Walk to Old Town",
    ],
    is_featured: false,
    reference: "IHP-C011",
    created_at: now,
    updated_at: now,
    images: imgs("p-011", ["interior-13.jpg", "interior-15.jpg", "interior-17.jpg"]),
  },
  {
    id: "p-012",
    slug: "baan-suan-pool-villa-chalong-rental",
    title: "Baan Suan — Pool Villa (Rental)",
    description:
      "A peaceful three-bedroom pool villa in a green Chalong setting, available for long-term rental. Spacious living, a large private pool and an easy drive to the island's southern beaches and Chalong Pier.",
    listing_type: "rent",
    status: "available",
    property_type: "Villa",
    area_slug: "chalong",
    price: 85000,
    rent_period: "month",
    bedrooms: 3,
    bathrooms: 3,
    living_area: 260,
    land_area: 520,
    address: "Chalong, Mueang Phuket",
    latitude: 7.847,
    longitude: 98.339,
    features: [
      "Large private pool",
      "Fully furnished",
      "Quiet green setting",
      "Near Chalong Pier",
      "Parking for 2",
      "Monthly maintenance included",
    ],
    is_featured: true,
    reference: "IHP-R012",
    created_at: now,
    updated_at: now,
    images: imgs("p-012", ["villa-5.png", "villa-1.png", "interior-4.jpg", "interior-18.jpg"]),
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: "b-2026-06-22-renting-villa-rawai",
    slug: "renting-luxury-pool-villa-rawai-2026",
    title: "Renting a Luxury Pool Villa in Rawai: What to Expect in 2026",
    excerpt:
      "Rawai is South Phuket's relaxed beach haven for expats and long-stay visitors. Here's what renting a private pool villa here really looks like in 2026.",
    content: `<p>On the southern tip of Phuket, Rawai has become one of the island's most loved areas for long-stay living — a laid-back blend of beachfront cafés, seafood markets, wellness studios and easy access to the island's most beautiful southern beaches. If you're thinking about renting a luxury pool villa here in 2026, here's what to expect.</p>
<h2>Why renters choose Rawai &amp; Nai Harn</h2>
<ul>
<li>Minutes from Nai Harn and Rawai beaches</li>
<li>A established, friendly expat and digital-nomad community</li>
<li>Fresh seafood markets, beach bars and yoga studios</li>
<li>Great value compared with the west-coast luxury belt</li>
</ul>
<h2>What your budget gets you</h2>
<p>Long-term monthly rentals for private pool villas in Rawai typically range widely depending on size, location and finish. At the premium end, larger family villas with resort-style outdoor space command higher rents but offer genuine space, privacy and quality.</p>
<figure>
<img src="/listings/rw-sasinee-villa-rw07/2.jpg" alt="Private pool at a luxury villa in Rawai, Phuket" />
<figcaption>A private pool villa in Rawai — resort-style outdoor living for long-term tenants.</figcaption>
</figure>
<p>A great current example is <a href="/properties/villa-sasinee-pool-villa-rawai-rw07">Villa Sasinee</a> — a 5-bedroom tropical pool villa with a 12m pool, jacuzzi, pool bar and large garden, just 7 minutes from Nai Harn Beach.</p>
<h2>Typical rental terms</h2>
<ul>
<li>Long-term contracts (usually 6–12 months) offer the best monthly rates</li>
<li>Standard terms are 2 months security deposit + 1 month advance rent</li>
<li>Utilities (electricity, water) are usually billed on top of the rent</li>
</ul>
<h2>Ready to find your villa?</h2>
<p>Browse our <a href="/rent">villas for rent</a>, or follow us for new arrivals on <a href="https://www.instagram.com/islanderhomephuket" target="_blank" rel="noopener">Instagram</a> and <a href="https://www.facebook.com/share/17zfFD16u2/?mibextid=wwXIfr" target="_blank" rel="noopener">Facebook</a>.</p>
<blockquote>Tell Islander Home Phuket what you're looking for and we'll match you with the right villa — usually within a few hours.</blockquote>`,
    cover_image: "/listings/rw-sasinee-villa-rw07/1.jpg",
    author: "Islander Home Team",
    tags: ["Rental", "Rawai", "Lifestyle"],
    published: true,
    published_at: "2026-06-22T12:00:00.000Z",
    created_at: now,
    updated_at: now,
  },
  {
    id: "b-2026-06-22-villa-investment-guide",
    slug: "phuket-villa-investment-guide-2026",
    title: "Phuket Villa Investment Guide 2026",
    excerpt:
      "Thinking of buying a pool villa in Phuket this year? Here's a clear, up-to-date guide to yields, ownership, costs and the areas worth watching in 2026.",
    content: `<p>Phuket remains one of Asia's most resilient lifestyle-and-investment property markets. If you're considering a villa in 2026, here's what actually matters — explained simply.</p>
<h2>Why Phuket in 2026?</h2>
<p>Strong international tourism, a growing community of long-stay residents and remote workers, and continued infrastructure investment all support both rental demand and long-term capital growth. Well-located pool villas remain the most sought-after asset class on the island.</p>
<h2>What returns can you expect?</h2>
<p>Gross rental yields on well-positioned pool villas typically range from <strong>6–9%</strong>, depending on location, management and occupancy. Net yields depend on running costs and how professionally the villa is marketed and maintained.</p>
<h2>How foreigners own a villa</h2>
<ul>
<li><strong>Leasehold</strong> — a registered long-term lease over the land with freehold ownership of the building.</li>
<li><strong>Thai company ownership</strong> — a properly structured company, always set up with professional legal guidance.</li>
</ul>
<p>We only work with vetted developments, clean Chanote titles and trusted local lawyers, so your due diligence is handled properly.</p>
<h2>Where the smart money is looking</h2>
<p>Bang Tao and Layan lead the luxury segment, Koh Kaew suits families near international schools, while Chalong, Rawai and Thalang offer strong value and lifestyle appeal. A great current example of a premium sea-view opportunity is <a href="/properties/walai-layan-sea-view-villas-bangtao-bt13">Walai Layan Sea View in Layan</a> — limited sea-view residences in a low-density gated community just minutes from the beach.</p>
<h2>Ready to explore?</h2>
<p>Browse our <a href="/buy">villas for sale</a> or follow us for new listings and market updates on <a href="https://www.instagram.com/islanderhomephuket" target="_blank" rel="noopener">Instagram</a> and <a href="https://www.facebook.com/share/17zfFD16u2/?mibextid=wwXIfr" target="_blank" rel="noopener">Facebook</a>.</p>
<blockquote>Speak to Islander Home Phuket for a no-obligation, area-by-area investment briefing tailored to your goals.</blockquote>`,
    cover_image: "/listings/bt-walai-layan-bt13/1.jpg",
    author: "Islander Home Team",
    tags: ["Investment", "Buying Guide", "Villas"],
    published: true,
    published_at: "2026-06-22T09:00:00.000Z",
    created_at: now,
    updated_at: now,
  },
  {
    id: "b-001",
    slug: "buying-property-in-phuket-foreigner-guide",
    title: "Buying Property in Phuket: A Foreigner's Guide",
    excerpt:
      "Everything overseas buyers need to know about freehold condos, leasehold land, due diligence and structuring a safe purchase in Phuket.",
    content: `<p>Phuket has long been Southeast Asia's premier island for lifestyle and investment property. But for first-time foreign buyers, Thailand's ownership rules can feel unfamiliar. This guide walks through the essentials.</p>
<h2>Can foreigners own property in Phuket?</h2>
<p>Yes — with important distinctions. Foreigners can own condominium units outright (freehold) within the <strong>49% foreign quota</strong> of any registered condo building. Land cannot be owned directly by foreigners, but there are well-established, secure structures for villa ownership.</p>
<h2>The two main routes for villas</h2>
<ul>
<li><strong>Leasehold</strong> — a registered 30-year lease (often with renewal options) over the land, with freehold ownership of the building itself.</li>
<li><strong>Thai company ownership</strong> — a properly structured Thai Limited Company, used with professional legal guidance.</li>
</ul>
<h2>Due diligence matters</h2>
<p>Before any purchase, we ensure a clean Chanote title, verified access, building permits and no encumbrances. Islander Home works only with vetted developments and trusted local lawyers.</p>
<blockquote>Our advice: never transfer funds before independent legal due diligence is complete.</blockquote>
<p>Speak to our team for a no-obligation consultation tailored to your goals.</p>`,
    cover_image: "/properties/villa-1.png",
    author: "Islander Home Team",
    tags: ["Buying Guide", "Legal", "Investment"],
    published: true,
    published_at: "2026-05-12T09:00:00.000Z",
    created_at: now,
    updated_at: now,
  },
  {
    id: "b-002",
    slug: "best-areas-to-invest-phuket-2026",
    title: "The Best Areas to Invest in Phuket in 2026",
    excerpt:
      "From Bang Tao's branded residences to Thalang's emerging value, here's where smart capital is moving on the island this year.",
    content: `<p>Location remains the single biggest driver of returns in Phuket real estate. Here's our 2026 outlook across the island's key areas.</p>
<h2>Bang Tao & Laguna</h2>
<p>The luxury benchmark. Strong rental yields, branded residences and consistent capital growth driven by international demand.</p>
<h2>Koh Kaew</h2>
<p>The family and long-stay favourite — close to international schools and malls, with modern condos at attractive entry prices.</p>
<h2>Thalang</h2>
<p>The value play. Larger plots and lower prices today, with airport proximity supporting long-term appreciation.</p>
<h2>Rawai & Chalong</h2>
<p>Lifestyle-led demand from expats and remote workers keeps occupancy high and supports resilient villa values.</p>
<p>Talk to Islander Home for an area-by-area investment briefing.</p>`,
    cover_image: "/properties/villa-3.png",
    author: "Islander Home Team",
    tags: ["Investment", "Areas", "Market"],
    published: true,
    published_at: "2026-05-26T09:00:00.000Z",
    created_at: now,
    updated_at: now,
  },
  {
    id: "b-003",
    slug: "rental-yields-phuket-villas-explained",
    title: "Rental Yields on Phuket Villas, Explained",
    excerpt:
      "How villa rental income really works in Phuket — gross vs net yields, seasonality, and how to maximise occupancy.",
    content: `<p>Rental income is a core part of many Phuket investment cases. Here's how to think about it realistically.</p>
<h2>Gross vs net yield</h2>
<p>Headline gross yields on well-located pool villas typically range from 6–9%. Net yields depend on management fees, maintenance, and occupancy.</p>
<h2>Seasonality</h2>
<p>High season (November–April) commands premium nightly rates; long-term tenancies smooth income across the year.</p>
<h2>Maximising occupancy</h2>
<ul>
<li>Professional photography and listing management</li>
<li>Strong locations near beaches and amenities</li>
<li>Quality furnishing and reliable maintenance</li>
</ul>
<p>Islander Home offers full rental management for owners — ask us how we can put your villa to work.</p>`,
    cover_image: "/properties/villa-6.png",
    author: "Islander Home Team",
    tags: ["Rental", "Investment"],
    published: true,
    published_at: "2026-06-02T09:00:00.000Z",
    created_at: now,
    updated_at: now,
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "l-001",
    name: "James Whitfield",
    email: "james.w@example.com",
    phone: "+44 7700 900123",
    message: "Interested in viewing Sunset Ridge — visiting Phuket next week.",
    property_id: "p-001",
    property_title: "Sunset Ridge — Sea-View Pool Villa",
    source: "property-detail",
    status: "new",
    created_at: "2026-06-05T11:20:00.000Z",
  },
  {
    id: "l-002",
    name: "Anya Petrova",
    email: "anya.p@example.com",
    phone: "+7 905 123 4567",
    message: "Looking for a long-term rental in Bang Tao for our family.",
    property_id: "p-007",
    property_title: "Palm Grove — Private Pool Villa (Rental)",
    source: "property-detail",
    status: "contacted",
    created_at: "2026-06-04T08:05:00.000Z",
  },
  {
    id: "l-003",
    name: "David Chen",
    email: "d.chen@example.com",
    phone: null,
    message: "What's the foreign freehold availability at The Quarter?",
    property_id: "p-005",
    property_title: "The Quarter — Modern 2-Bed Condo",
    source: "contact-page",
    status: "new",
    created_at: "2026-06-06T15:42:00.000Z",
  },
];
