// AUTO-GENERATED by scripts/import-listings.mjs — do not edit by hand.
// Source: Notion CSV exports in data/notion/. Landlord-contact columns are excluded.
import type { Property } from "./types";

export const NOTION_PROPERTIES: Property[] = [];
